[2024-07-18T15:27:33.113+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T15:27:33.146+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_fill_procedure.fill_dm_account_turnover manual__2024-07-18T15:21:35.554818+00:00 [queued]>
[2024-07-18T15:27:33.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_fill_procedure.fill_dm_account_turnover manual__2024-07-18T15:21:35.554818+00:00 [queued]>
[2024-07-18T15:27:33.154+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-18T15:27:33.163+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fill_dm_account_turnover> on 2024-07-18 15:21:35.554818+00:00
[2024-07-18T15:27:33.169+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_fill_procedure', 'fill_dm_account_turnover', 'manual__2024-07-18T15:21:35.554818+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/create_and_fill_proc.py', '--cfg-path', '/tmp/tmpq6e0mapu']
[2024-07-18T15:27:33.172+0000] {standard_task_runner.py:91} INFO - Job 415: Subtask fill_dm_account_turnover
[2024-07-18T15:27:33.172+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2023) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-18T15:27:33.173+0000] {standard_task_runner.py:63} INFO - Started process 2024 to run task
[2024-07-18T15:27:33.208+0000] {task_command.py:426} INFO - Running <TaskInstance: run_fill_procedure.fill_dm_account_turnover manual__2024-07-18T15:21:35.554818+00:00 [running]> on host 7c7e02e57379
[2024-07-18T15:27:33.279+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_fill_procedure' AIRFLOW_CTX_TASK_ID='fill_dm_account_turnover' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T15:21:35.554818+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T15:21:35.554818+00:00'
[2024-07-18T15:27:33.280+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T15:27:33.298+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-18T15:27:33.304+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T15:27:33.305+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_and_fill_proc.py", line 144, in fill_dm_account_turnover
    cursor.execute(sql)
psycopg2.errors.AmbiguousColumn: column reference "log_id" is ambiguous
LINE 3:             returning log_id
                              ^
DETAIL:  It could refer to either a PL/pgSQL variable or a table column.
QUERY:  insert into logs.logs(start_time, status)
            values (start_time, 'Start_fill_turnover')
            returning log_id
CONTEXT:  PL/pgSQL function inline_code_block line 7 at SQL statement

[2024-07-18T15:27:33.337+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=run_fill_procedure, task_id=fill_dm_account_turnover, run_id=manual__2024-07-18T15:21:35.554818+00:00, execution_date=20240718T152135, start_date=20240718T152733, end_date=20240718T152733
[2024-07-18T15:27:33.356+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 415 for task fill_dm_account_turnover (column reference "log_id" is ambiguous
LINE 3:             returning log_id
                              ^
DETAIL:  It could refer to either a PL/pgSQL variable or a table column.
QUERY:  insert into logs.logs(start_time, status)
            values (start_time, 'Start_fill_turnover')
            returning log_id
CONTEXT:  PL/pgSQL function inline_code_block line 7 at SQL statement
; 2024)
[2024-07-18T15:27:33.390+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-18T15:27:33.410+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-07-18T15:27:33.440+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T15:27:33.444+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
