[2024-07-18T18:50:55.481+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T18:50:55.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_fill_procedure.end_process manual__2024-07-18T18:50:26.453660+00:00 [queued]>
[2024-07-18T18:50:55.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_fill_procedure.end_process manual__2024-07-18T18:50:26.453660+00:00 [queued]>
[2024-07-18T18:50:55.518+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-18T18:50:55.530+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): end_process> on 2024-07-18 18:50:26.453660+00:00
[2024-07-18T18:50:55.536+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_fill_procedure', 'end_process', 'manual__2024-07-18T18:50:26.453660+00:00', '--job-id', '479', '--raw', '--subdir', 'DAGS_FOLDER/create_and_fill_proc.py', '--cfg-path', '/tmp/tmpgijgyzqo']
[2024-07-18T18:50:55.538+0000] {standard_task_runner.py:91} INFO - Job 479: Subtask end_process
[2024-07-18T18:50:55.548+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11572) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-18T18:50:55.549+0000] {standard_task_runner.py:63} INFO - Started process 11573 to run task
[2024-07-18T18:50:55.576+0000] {task_command.py:426} INFO - Running <TaskInstance: run_fill_procedure.end_process manual__2024-07-18T18:50:26.453660+00:00 [running]> on host 7c7e02e57379
[2024-07-18T18:50:55.686+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_fill_procedure' AIRFLOW_CTX_TASK_ID='end_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T18:50:26.453660+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T18:50:26.453660+00:00'
[2024-07-18T18:50:55.687+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T18:50:55.709+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-18T18:50:55.732+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-18T18:50:55.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T18:50:55.743+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=run_fill_procedure, task_id=end_process, run_id=manual__2024-07-18T18:50:26.453660+00:00, execution_date=20240718T185026, start_date=20240718T185055, end_date=20240718T185055
[2024-07-18T18:50:55.779+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-18T18:50:55.807+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T18:50:55.809+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
