[2024-07-18T15:50:07.275+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T15:50:07.303+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_fill_procedure.extract_and_load_process manual__2024-07-18T15:44:50.735231+00:00 [queued]>
[2024-07-18T15:50:07.310+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_fill_procedure.extract_and_load_process manual__2024-07-18T15:44:50.735231+00:00 [queued]>
[2024-07-18T15:50:07.311+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-18T15:50:07.325+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_process> on 2024-07-18 15:44:50.735231+00:00
[2024-07-18T15:50:07.332+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_fill_procedure', 'extract_and_load_process', 'manual__2024-07-18T15:44:50.735231+00:00', '--job-id', '435', '--raw', '--subdir', 'DAGS_FOLDER/create_and_fill_proc.py', '--cfg-path', '/tmp/tmptzwqmbet']
[2024-07-18T15:50:07.334+0000] {standard_task_runner.py:91} INFO - Job 435: Subtask extract_and_load_process
[2024-07-18T15:50:07.346+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5114) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-18T15:50:07.347+0000] {standard_task_runner.py:63} INFO - Started process 5115 to run task
[2024-07-18T15:50:07.377+0000] {task_command.py:426} INFO - Running <TaskInstance: run_fill_procedure.extract_and_load_process manual__2024-07-18T15:44:50.735231+00:00 [running]> on host 7c7e02e57379
[2024-07-18T15:50:07.455+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_fill_procedure' AIRFLOW_CTX_TASK_ID='extract_and_load_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T15:44:50.735231+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T15:44:50.735231+00:00'
[2024-07-18T15:50:07.456+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T15:50:11.325+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-18T15:50:13.055+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-18T15:50:14.251+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-18T15:50:15.389+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-18T15:50:15.717+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-18T15:50:16.946+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T15:50:16.948+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_and_fill_proc.py", line 112, in extract_and_load_task
    df = df.dropDuplicates(["data_actual_date", "currency_rk"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/dataframe.py", line 4219, in dropDuplicates
    jdf = self._jdf.dropDuplicates(self._jseq(subset))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Cannot resolve column name "data_actual_date" among (CHAPTER, CHAPTER_NAME, SECTION_NUMBER, SECTION_NAME, SUBSECTION_NAME, LEDGER1_ACCOUNT, LEDGER1_ACCOUNT_NAME, LEDGER_ACCOUNT, LEDGER_ACCOUNT_NAME, CHARACTERISTIC, START_DATE, END_DATE).
[2024-07-18T15:50:16.970+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=run_fill_procedure, task_id=extract_and_load_process, run_id=manual__2024-07-18T15:44:50.735231+00:00, execution_date=20240718T154450, start_date=20240718T155007, end_date=20240718T155016
[2024-07-18T15:50:16.986+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 435 for task extract_and_load_process (Cannot resolve column name "data_actual_date" among (CHAPTER, CHAPTER_NAME, SECTION_NUMBER, SECTION_NAME, SUBSECTION_NAME, LEDGER1_ACCOUNT, LEDGER1_ACCOUNT_NAME, LEDGER_ACCOUNT, LEDGER_ACCOUNT_NAME, CHARACTERISTIC, START_DATE, END_DATE).; 5115)
[2024-07-18T15:50:16.999+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-18T15:50:17.011+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-07-18T15:50:17.024+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T15:50:17.030+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
