[2024-07-16T22:51:33.941+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T22:51:33.964+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T22:45:30.620580+00:00 [queued]>
[2024-07-16T22:51:33.972+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T22:45:30.620580+00:00 [queued]>
[2024-07-16T22:51:33.973+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-07-16T22:51:33.987+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_process> on 2024-07-16 22:45:30.620580+00:00
[2024-07-16T22:51:33.993+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_pgsql', 'extract_and_load_process', 'manual__2024-07-16T22:45:30.620580+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/from_csv_to_pgsql.py', '--cfg-path', '/tmp/tmpgu7rx5zx']
[2024-07-16T22:51:33.996+0000] {standard_task_runner.py:91} INFO - Job 341: Subtask extract_and_load_process
[2024-07-16T22:51:33.998+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=720) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-16T22:51:33.999+0000] {standard_task_runner.py:63} INFO - Started process 721 to run task
[2024-07-16T22:51:34.042+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T22:45:30.620580+00:00 [running]> on host 77e6c655c0d2
[2024-07-16T22:51:34.142+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_pgsql' AIRFLOW_CTX_TASK_ID='extract_and_load_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T22:45:30.620580+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T22:45:30.620580+00:00'
[2024-07-16T22:51:34.143+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T22:51:39.915+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T22:51:39.917+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_csv_to_pgsql.py", line 117, in extract_and_load_task
    df.withColumn('ON_DATE',to_date(col('ON_DATE')), "dd.MM.yyyy")
TypeError: DataFrame.withColumn() takes 3 positional arguments but 4 were given
[2024-07-16T22:51:39.933+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_pgsql, task_id=extract_and_load_process, run_id=manual__2024-07-16T22:45:30.620580+00:00, execution_date=20240716T224530, start_date=20240716T225133, end_date=20240716T225139
[2024-07-16T22:51:39.962+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 341 for task extract_and_load_process (DataFrame.withColumn() takes 3 positional arguments but 4 were given; 721)
[2024-07-16T22:51:40.006+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T22:51:40.053+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T22:51:40.063+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
