[2024-07-16T21:00:00.535+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T21:00:00.579+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T20:59:51.566013+00:00 [queued]>
[2024-07-16T21:00:00.593+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T20:59:51.566013+00:00 [queued]>
[2024-07-16T21:00:00.594+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-16T21:00:00.612+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_process> on 2024-07-16 20:59:51.566013+00:00
[2024-07-16T21:00:00.620+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_pgsql', 'extract_and_load_process', 'manual__2024-07-16T20:59:51.566013+00:00', '--job-id', '320', '--raw', '--subdir', 'DAGS_FOLDER/from_csv_to_pgsql.py', '--cfg-path', '/tmp/tmpqss43jwt']
[2024-07-16T21:00:00.623+0000] {standard_task_runner.py:91} INFO - Job 320: Subtask extract_and_load_process
[2024-07-16T21:00:00.624+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4138) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-16T21:00:00.626+0000] {standard_task_runner.py:63} INFO - Started process 4139 to run task
[2024-07-16T21:00:00.691+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T20:59:51.566013+00:00 [running]> on host 347bc1cf7978
[2024-07-16T21:00:00.779+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_pgsql' AIRFLOW_CTX_TASK_ID='extract_and_load_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T20:59:51.566013+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T20:59:51.566013+00:00'
[2024-07-16T21:00:00.781+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T21:00:04.635+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T21:00:04.637+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_csv_to_pgsql.py", line 98, in extract_and_load_task
    df = spark.read.csv(f'/opt/airflow/files/{file}', sep=';', header=True, schema=f'schema_{file_name}')
                                                                                             ^^^^^^^^^
UnboundLocalError: cannot access local variable 'file_name' where it is not associated with a value
[2024-07-16T21:00:04.654+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_pgsql, task_id=extract_and_load_process, run_id=manual__2024-07-16T20:59:51.566013+00:00, execution_date=20240716T205951, start_date=20240716T210000, end_date=20240716T210004
[2024-07-16T21:00:04.676+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 320 for task extract_and_load_process (cannot access local variable 'file_name' where it is not associated with a value; 4139)
[2024-07-16T21:00:04.706+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T21:00:04.737+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T21:00:04.741+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
